echo;
echo "Program do przetwarzania obrazow PGM i PPM";
echo;
echo "Podstawowe opcje:";
echo "-i <nazwa_pliku> --- nazwa pliku do wczytania (jesli zamiast nazwy podany bedzie znak '-' to zamiast z pliku obraz bedzie wczytywany ze standardowego wejscia";
echo "-o <nazwa_pliku> --- nazwa pliku do zapisu (jesli zamiast nazwy podany bedzie znak '-' to zamiast do pliku obraz bedzie wypisany na standardowym wyjsciu";
echo "-d ----------------- obraz po przetworzeniu powinien zostac wyswietlony";
echo "-m <kolor> --------- wybierz kolor do przetwarzania: r - czerwony, g - zielony, b - niebieski, s - konwersja do szarosci, brak opcji powoduje wykonanie operacji na wszyskich kolorach";
echo;
echo "Operacje szczegolowe:";
echo "-n ------------------- negatyw";
echo "-p <prog> ------------ progowanie z danym progiem, pamietaj ze prog jest w % (od 0 do 100)";
echo "-pc <prog> ----------- progowanie czerni z danym progiem, pamietaj ze prog jest w % (od 0 do 100)";
echo "-pb <prog> ----------- progowanie bieli z danym progiem, pamietaj ze prog jest w % (od 0 do 100)";
echo "-g <wspolczynnik> ---- korekcja gamma z danym wspolczynnikiem, pamietaj ze wspolczynnik musi byc nieujemny";
echo "-z <czern> <biel> ---- zmiana poziomow, pamietaj ze czern i biel sa w % (0,100) i ze czern < biel";
echo "-k ------------------- konturowanie";
echo "-rx ------------------ rozmywanie poziome";
echo "-ry ------------------ rozmywanie pionowe";
echo "-h ------------------- rozciaganie histogramu";
echo;
echo "Kolejnosc w jakiej moga wystapic opcje jest dowolna.";
echo "Opcja -i musi sie pojawic przy wywolaniu programu.";
echo "Znak '-' jest czescia kazdej opcji.";
echo "Przykladowe wywolanie programu: ./a.out -i nazwa_wczytaj -m g -k -o nazwa_zapis -d";
echo "Gdy pojawi sie opcaja -m dla obrazka PGM zostanie ona zignorowana!";
echo;
echo "Kody bledow (w razie gdyby cos poszlo nie tak): ";
echo "Niepoprawna opcja: -1";
echo "Brak nazwy:::::::: -2";
echo "Brak wartosci::::: -3";
echo "Brak pliku:::::::: -4";
echo;
echo;
echo;
echo;
echo;